# Generated by Django 4.1 on 2022-12-02 21:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aplicacion_prueba', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostBLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('descriction', models.TextField(verbose_name='Descripsion')),
                ('img', models.ImageField(blank=True, max_length=150, null=True, upload_to='img', verbose_name='Imagen')),
                ('complete', models.BooleanField(default=True, verbose_name='completado')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='persona',
        ),
    ]
