# Generated by Django 4.1.3 on 2022-12-02 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion_prueba', '0010_alter_forms_create'),
    ]

    operations = [
        migrations.AddField(
            model_name='forms',
            name='title',
            field=models.CharField(default=1, max_length=250, verbose_name='title'),
            preserve_default=False,
        ),
    ]
