# Generated by Django 4.1.3 on 2022-12-02 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion_prueba', '0011_forms_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forms',
            name='title',
            field=models.CharField(max_length=250, unique=True, verbose_name='title'),
        ),
    ]
