# Generated by Django 4.1.3 on 2022-12-03 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion_prueba', '0013_remove_forms_question_question_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='total_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=2),
        ),
        migrations.AddField(
            model_name='question',
            name='points',
            field=models.CharField(choices=[(5, 5), (10, 10), (15, 15), (20, 20)], default=1, max_length=1, verbose_name='puntos'),
            preserve_default=False,
        ),
    ]
