# Generated by Django 4.1.3 on 2022-12-03 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion_prueba', '0016_alter_question_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response_question', to='aplicacion_prueba.question'),
        ),
    ]
