# Generated by Django 4.1.3 on 2022-12-03 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion_prueba', '0017_alter_response_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='total_score',
            field=models.IntegerField(default=0, verbose_name='points_total_score'),
        ),
    ]
