# Generated by Django 4.1.3 on 2022-12-04 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion_prueba', '0020_forms_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.TextField(verbose_name='answers')),
                ('correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers_question', to='aplicacion_prueba.question')),
            ],
            options={
                'verbose_name': 'answers',
            },
        ),
        migrations.CreateModel(
            name='resuls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='forms',
            name='time',
            field=models.IntegerField(default=0, help_text='Time to', verbose_name='time'),
        ),
        migrations.DeleteModel(
            name='Response',
        ),
        migrations.AddField(
            model_name='resuls',
            name='forms',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resuls_forms', to='aplicacion_prueba.forms'),
        ),
        migrations.AddField(
            model_name='resuls',
            name='quetions',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resuls_quetions', to='aplicacion_prueba.question'),
        ),
    ]
