# Generated by Django 4.1.3 on 2022-12-04 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion_prueba', '0021_answers_resuls_alter_forms_time_delete_response_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resuls',
            name='score',
            field=models.FloatField(default=0, null=True),
        ),
    ]
