# Generated by Django 4.1.3 on 2022-12-05 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion_prueba', '0023_forms_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='forms',
            name='descriction',
            field=models.TextField(default=1, verbose_name='descriction'),
            preserve_default=False,
        ),
    ]
