# Generated by Django 4.1.3 on 2022-12-05 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion_prueba', '0024_forms_descriction'),
    ]

    operations = [
        migrations.AddField(
            model_name='forms',
            name='nivel',
            field=models.CharField(choices=[('basic', 'basic'), ('medium', 'medium'), ('high', 'high'), ('very high', 'very high')], default=1, max_length=10, verbose_name='nivel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='forms',
            name='complete',
            field=models.BooleanField(default=False, verbose_name='complete'),
        ),
    ]
