# Generated by Django 4.1.3 on 2022-12-07 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion_prueba', '0025_forms_nivel_alter_forms_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='form',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='forms_answer', to='aplicacion_prueba.forms'),
            preserve_default=False,
        ),
    ]
