# Generated by Django 4.1.3 on 2022-12-08 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion_prueba', '0029_alter_question_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='resuls',
            name='answers',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='resuls_answers', to='aplicacion_prueba.answers'),
            preserve_default=False,
        ),
    ]
