# Generated by Django 4.1.3 on 2022-12-08 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion_prueba', '0031_resuls_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answers',
            name='form',
        ),
    ]
