# Generated by Django 4.1.3 on 2022-12-08 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion_prueba', '0032_remove_answers_form'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resuls',
            name='answers',
        ),
        migrations.RemoveField(
            model_name='resuls',
            name='forms',
        ),
    ]
