# Generated by Django 4.1.3 on 2022-12-08 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion_prueba', '0033_remove_resuls_answers_remove_resuls_forms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='points',
            field=models.IntegerField(choices=[(5, 5), (10, 10), (20, 20)], verbose_name='point value'),
        ),
    ]
