# Generated by Django 4.1.3 on 2022-12-13 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion_prueba', '0034_alter_question_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resuls',
            name='quetions',
        ),
        migrations.AddField(
            model_name='resuls',
            name='quiz',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Resuls', to='aplicacion_prueba.forms'),
            preserve_default=False,
        ),
    ]
