# Generated by Django 4.1.3 on 2022-12-13 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion_prueba', '0036_remove_forms_complete_forms_total_score_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='resuls',
            name='complete',
            field=models.BooleanField(default=False, verbose_name='complete'),
        ),
    ]
