# Generated by Django 4.1.3 on 2022-12-13 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion_prueba', '0037_resuls_complete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='points',
        ),
    ]
