# Generated by Django 4.1.4 on 2022-12-23 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aplicacion_prueba", "0039_rename_forms_quiz"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="imagen",
            field=models.ImageField(
                default="questions.png", upload_to="", verbose_name="imagen_profile"
            ),
        ),
    ]
