# Generated by Django 4.1.4 on 2022-12-23 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aplicacion_prueba", "0040_alter_profile_imagen"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resuls",
            name="score",
            field=models.IntegerField(default=0, null=True),
        ),
    ]
