# Generated by Django 4.1.4 on 2022-12-23 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aplicacion_prueba", "0041_alter_resuls_score"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resuls",
            name="score",
            field=models.FloatField(default=0, null=True),
        ),
    ]
