# Generated by Django 4.1.4 on 2022-12-23 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aplicacion_prueba", "0042_alter_resuls_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="number_of_questions",
            field=models.IntegerField(default=0, verbose_name="number of questions"),
        ),
    ]
